# Generated by Django 3.2.8 on 2021-10-30 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resale_app', '0002_rename_id_solditemswomen_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solditemswomen',
            name='item_id',
            field=models.TextField(db_column='item_id', primary_key=True, serialize=False),
        ),
    ]
