# Generated by Django 3.2.8 on 2021-10-30 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resale_app', '0003_alter_solditemswomen_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solditemswomen',
            name='link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='solditemswomen',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
