# Generated by Django 3.2.8 on 2021-10-30 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resale_app', '0004_auto_20211030_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solditemswomen',
            name='condition',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='solditemswomen',
            name='date_added',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='solditemswomen',
            name='list_price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='solditemswomen',
            name='sale_price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='solditemswomen',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
